;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 ascii.inc                                  ;
;                                ASCII symbols                               ;
;                                Include File                                ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; This file contains the ASCII table.
;
; Revision History:
;     11/22/23  Adam Krivka      initial revision

ASCII_NUL       	.equ     0	; Null
ASCII_TAB 			.equ     9	; Horizontal Tab
ASCII_SPACE 		.equ    32	; Space
ASCII_ZERO 			.equ    48	; Zero
ASCII_MINUS 		.equ    45	; Minus